# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  # name: default
  vmImage: windows-latest

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: 'install'
        workingDir: '$(System.DefaultWorkingDirectory)'
    - task: Npm@1
      displayName: 'npm build'
      inputs:
        command: 'custom'
        workingDir: '$(System.DefaultWorkingDirectory)'
        customCommand: 'run build'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/build'
        Contents: '**'
        TargetFolder: '$(System.ArtifactsDirectory)'
#     - task: PublishBuildArtifacts@1
#       inputs:
#         PathtoPublish: '$(Build.ArtifactstagingDirectory)'
#         ArtifactName: 'drop'
#         publishLocation: 'Container'
    
# - stage: release
#   jobs:
#   - job: release
#     steps:
#     - task: DownloadBuildArtifacts@0
#       inputs:
#         buildType: 'current'
#         downloadType: 'single'
#         artifactName: 'drop'
#         downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Free Trial(8c0e0cc2-31fd-4273-8442-8e28c950c2de)'
        appType: 'webApp'
        appName: 'ish-learn1'
        package: '$(System.ArtifactsDirectory)'
        deploymentMethod: 'auto'