# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 7.0.100'
  inputs:
    version: '7.0.100'
    packageType: sdk

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: Docker@2
  displayName: 'Login to Registry'
  inputs:
    containerRegistry: 'serviceconnectiondocker'
    command: 'login'
  condition: succeeded()

- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'serviceconnectiondocker'
    repository: 'serviceconnectiondocker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'tag1'

- task: CopyFiles@2
  displayName: 'Copy Helm Chart to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: 'DevOps/AKS/Helm'
    Contents: |
      **
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Helm files'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: DeploymentScripts
